name: CI for constant-folding

on: # when this action should be triggered?
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: # jobs are made of steps
  build:
    # Define the OS our workflow should run on
    runs-on: ${{ matrix.os }}

    strategy:
      # To test across multiple language versions
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps: # Clone the repo. See https://github.com/actions/checkout
    - uses: actions/checkout@v2
    # Example of using an environment variable
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v1 # Install node. See https://github.com/actions/setup-node
      with:
        node-version: ${{ matrix.node-version }}
    # Install a project with a clean slate
    - run: npm ci
    - run: npm test
      # Environment variables
      env:
        CI: true
